title: nextnormal.academy@GitHub
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: gbeine/minimal-mistakes

# Outputting
permalink: /:categories/:title/
#paginate: 5 # amount of posts to show
#paginate_path: /page:num/
timezone: Europe/Berlin # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock
  - .bundle
  - vendor
  - .ztr-directory
keep_files:
  - .git

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      read_time: false
      author_profile: false
      share: false
      comments: false
      sidebar:
        nav: "sidebar"
  # _schemes
  - scope:
      path: ""
      type: schemes
    values:
      layout: single
      read_time: false
      author_profile: false
      share: false
      comments: false
      sidebar:
        nav: "sidebar"

collections:
  schemes:
    output: true
    permalink: /:collection/:path/

category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/
